#!/bin/bash

samplePassword=501103
GREEN='\033[0;32m'
RESET='\033[0m'

parse_push_target_branch() {
    push_cmd=$(tail -1 $HOME/.zsh_history)
    target_branch=$(echo $push_cmd | awk -F' ' '{print $5}')

    echo "$target_branch"
}

echo ""
echo ""
echo -e "Release 상태, ${GREEN}$(parse_push_target_branch)${RESET}에 푸시하는게 맞는지 확인 필요!"
echo ""
echo ""

while [ 1 ]
    do
        read -p "비밀번호 입력: " password < /dev/tty

        if [ "$password" == "$samplePassword" ]; then
            exit 0
        else
            echo "잘못된 비밀번호"
        fi
done

exit 1 # exit 값이 0이 아니면 푸시를 취소한다.
