#!/bin/bash

samplePassword=501103
GREEN='\033[0;32m'
RESET='\033[0m'

parse_git_branch() {
    if git rev-parse --git-dir > /dev/null 2>&1
    then
        currentBranch=$(git branch 2>/dev/null | sed -n '/^\*/s/^\* //p') # 현재 HEAD 브랜치 즉, 커밋 하려는 브랜치를 알아낸다.
    else
        return 0
    fi

    echo -e "$currentBranch"
}

echo ""
echo ""
echo -e "Release 상태, ${GREEN}$(parse_git_branch)${RESET}에 커밋하는게 맞는지 확인 필요!"
echo ""
echo ""

while [ 1 ]
    do
        read -p "비밀번호 입력: " password < /dev/tty

        if [ "$password" == "$samplePassword" ]; then
            exit 0
        else
            echo "잘못된 비밀번호"
        fi
done

exit 1 # exit 값이 0이 아니면 커밋을 취소한다.
